### ISSUE TITLE
CheckList

### ISSUE THREAD

**Issue by indraraj26** [indraraj26/ion-camera#1]
- [X] Service to access camera method -> through directive return actual value and service return promise.
- [X] Handle permission -> i will return no permission and its up to dev how he is going to handle permission.
- [X] Handle through gallery and file explorer.
- [X] readme
- [X] demo application
- [ ] upload through http return progress and response.
